[build-system]
requires = ["scikit-build-core >=0.10", "nanobind >=2.2.0"]
build-backend = "scikit_build_core.build"

[project]
name = "tdjson"
dynamic = ["version"]
description = "High-performance Python bindings for TDLib with native speed and prebuilt binaries for Linux, Windows, and macOS"
readme = "README.md"
authors = [{ name = "AYMEN", email = "let.me.code.safe@gmail.com" }]
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.9"
keywords = [
    "tdlib",
    "telegram",
    "tdlib-binding",
    "python-binding",
    "native",
    "high-performance",
    "prebuilt-binaries",
    "linux",
    "windows",
    "macos",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.15",
    "Programming Language :: C++",
    "Topic :: Communications",
    "Topic :: Communications :: Chat",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: MacOS",
]

[project.urls]
Source = "https://github.com/AYMENJD/tdjson"
Tracker = "https://github.com/AYMENJD/tdjson/issues"

[tool.scikit-build]
build-dir = "build/{wheel_tag}"

[tool.scikit-build.metadata.version]
provider = "scikit_build_core.metadata.regex"
input = "tdjson/_version.py"

[tool.scikit-build.cmake.define]
CMAKE_BUILD_TYPE = "Release"

[tool.cibuildwheel]
build-verbosity = 1
build-frontend = "build[uv]"
skip = "*musllinux*"
archs = ["native"]

[tool.cibuildwheel.linux]
before-all = ".github/workflows/scripts/before-all-linux-64.sh"
manylinux-x86_64-image = "manylinux2014"
manylinux-aarch64-image = "manylinux2014"

[tool.cibuildwheel.windows]
before-build = "pip install delvewheel"
repair-wheel-command = "delvewheel repair -w {dest_dir} {wheel}"
